Add support for input file to progdiff.

diff --git a/progdiff b/progdiff
--- a/progdiff
+++ b/progdiff
@@ -2,26 +2,22 @@
 #
 # Diff the output of a candidate program against a solution program.
 #
-# Usage: progdiff solution candidate [ -o 'options' ]
+# Usage: progdiff solution candidate [ -o 'options' ] [ prefix ]
 #   -o default string of options required by the solution and candidate programs to generate 
 #       the required output
 
 usage () {                                                       # print usage message & terminate
-    echo "Usage: $(basename "$0") solution candidate [ -o 'options' ]" >&2
+    echo "Usage: $(basename "$0") solution candidate [ -o 'options' ] [ prefix ]" >&2
     exit 1
 }
 
 progdiff_run () {
-    touch "${1}.in"
-
     $("${solution}" ${options} < "${1}.in" > "${1}.out")
 
     regress "${candidate}" -o "${options}" -p "${1}"
 
     exitstatus="${?}"
 
-    # Clean up
-    rm -f "${1}.in"
     rm -f "${1}.out"
 }
 
@@ -48,14 +44,25 @@ if [ "${?}" -ne 0 ]; then                                       # candidate prog
 fi
 
 options=""
+prefix=""
 while [ ${#} -gt 0 ]; do                                        # process command-line arguments
     case "${1}" in
     '-o') options="${2}"; shift ;;                              # options ?
     *)
+        prefix=$1 ;;
     esac
     shift
 done
 
-progdiff_run "test-$RANDOM"                                     # generate random prefix for test
+if [ -z $prefix ]; then
+    prefix="test-$RANDOM"                                       # generate random prefix for test
+    touch "${prefix}.in"                                        # hack: dummy input file for regress 
+    
+    progdiff_run "${prefix}"
+
+    rm -f "${prefix}.in"                                        # cleanup dummy input file
+else
+    progdiff_run "${prefix}"
+fi
 
 exit $exitstatus                                                # propogate exist status from regress  
